### PR TITLE
youtube.com

### PR DESCRIPTION
**Pull request by brucehuanglove**
Thanks for reviewing

### CODE REVIEW

**Comment by Riajyuu** [comment]
Thanks for your time.
Could you explain a bit where do they targeted?

**Comment by brucehuanglove** [comment]
s.ytimg.com script for youtube home page.
s.ytimg.com xhr for youtube video playing page.

**Comment by brucehuanglove** [comment]
more precisely: 
` s.ytimg.com script allow` for youtube user home page.
`s.ytimg.com xhr allow` for page comment area

maybe, the second can be optional?

**Review by Riajyuu — APPROVED** [review]
I'll merge it later. Thx.

**Pull request merged**
